### ISSUE TITLE
NameError: name 'Confirm' is not defined

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-vi#109]
```
pyodide.asm.js:14 Uncaught PythonError: Traceback (most recent call last):
  File "/build/actions/hierarchy.py", line 119, in onClick
NameError: name 'Confirm' is not defined

    at new_error (pyodide.asm.js:14:248620)
    at pyodide.asm.wasm:0x1b9500
    at pyodide.asm.wasm:0x1b95f7
    at Object.Module.callPyObjectKwargs (pyproxy.gen.js:393:12)
    at Object.Module.callPyObject (pyproxy.gen.js:399:17)
    at PyProxyClass.apply (pyproxy.gen.js:1190:19)
    at Object.apply (pyproxy.gen.js:1072:18)
```

**Comment by phorward** [comment]
Fixed by 47a7104
